# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        ModelBundle\Entity\User:
           algorithm: md5
           encode_as_base64: false
           iterations: 0


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        # fos_userbundle:
        #     id: fos_user.user_provider.username
        entity_provider:
           entity:
             class: ModelBundle:User
             property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
               check_path: /login_check
               require_previous_session: false
               success_handler: lexik_jwt_authentication.handler.authentication_success
               failure_handler: lexik_jwt_authentication.handler.authentication_failure
        register:
            pattern:  ^/register
            stateless: true
            anonymous: true
        api:
            pattern:  ^/api
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                   - app.jwt_token_authenticator  
        refresh:
            pattern:  ^/token/refresh
            stateless: true
            anonymous: true  

        # main:
        #     pattern: ^/
        #     form_login:
        #         provider: fos_userbundle
        #         csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
        #     logout:       true
        #     anonymous:    true
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }  
        - { path: ^/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
