<?php

namespace ModelBundle\Repository;

/**
 * FlashSaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlashSaleRepository extends \Doctrine\ORM\EntityRepository
{
}
