<?php

namespace ModelBundle\Repository;

/**
 * FollowStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowStateRepository extends \Doctrine\ORM\EntityRepository
{
}
