<?php

namespace ModelBundle\Repository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreChainRepository extends \Doctrine\ORM\EntityRepository
{
}
