<?php

namespace ModelBundle\Repository;

/**
 * StoreLoyaltyCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreLoyaltyCardRepository extends \Doctrine\ORM\EntityRepository
{
}
