<?php

namespace ModelBundle\Repository;

/**
 * UserBonusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBonusRepository extends \Doctrine\ORM\EntityRepository
{
}
