<?php

namespace ModelBundle\Repository;

/**
 * UserLoyaltyCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserLoyaltyCardRepository extends \Doctrine\ORM\EntityRepository
{
}
